/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/pages/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    "bg-popover",
    "text-popover-foreground",
    "rounded-md",
    "border",
    "p-4",
    "shadow-md",
    "z-50",
    "w-72",
    "origin-[--radix-popover-content-transform-origin]",
    "outline-hidden",
    "flex",
    "flex-col",
    "sm:flex-row",
    "space-y-4",
    "sm:space-x-4",
    "sm:space-y-0",
    "justify-center",
    "pt-1",
    "relative",
    "items-center",
    "text-sm",
    "font-medium",
    "space-x-1",
    "h-7",
    "w-7",
    "bg-transparent",
    "p-0",
    "opacity-50",
    "hover:opacity-100",
    "absolute",
    "left-1",
    "right-1",
    "w-full",
    "border-collapse",
    "space-y-1",
    "w-9",
    "font-normal",
    "text-[0.8rem]",
    "mt-2",
    "h-9",
    "text-center",
    "bg-accent",
    "text-accent-foreground",
    "text-muted-foreground",
    "opacity-50",
    "rounded-md",
    "bg-primary",
    "text-primary-foreground",
    "hover:bg-primary",
    "hover:text-primary-foreground",
    "focus:bg-primary",
    "focus:text-primary-foreground",
    "invisible",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}; 